### ISSUE TITLE
Orchard.OpenId, Use Jwt ,has get token but authorize doesn't work

### ISSUE THREAD

**Issue by yiji** [OrchardCMS/Orchard2#726] opened 2017-04-27 07:18 UTC
i want to use openid module create jwt token , to visited protected resource. i has config module below
![default](https://cloud.githubusercontent.com/assets/6138770/25471692/c896959c-2b5a-11e7-8069-0e8b0a9c8f72.png)

![default](https://cloud.githubusercontent.com/assets/6138770/25471794/3404d1b8-2b5b-11e7-9466-48e030c2366c.png)

I have get access token, but authorize doesn't work,redirection to login
![default](https://cloud.githubusercontent.com/assets/6138770/25471623/8f8fbce2-2b5a-11e7-8052-964b0e6d64d1.png)

localhost:2918/Orchard.Demo/ContentApi/GetAuthorizedById/1

![default](https://cloud.githubusercontent.com/assets/6138770/25472166/b3566ffc-2b5c-11e7-9fdc-ff3929af4f51.png)

localhost:2918/Orchard.OpenId/UserInfo/Me

![default](https://cloud.githubusercontent.com/assets/6138770/25472909/dd4e5362-2b5f-11e7-9b15-54c21295c7a9.png)

**Comment by jersiovic** [comment] 2017-04-27 15:46
You are requesting contentitem with id=1 Are you sure is there a content ítem with id=1? 
Have you tried to log in as admin user through a browser and access that url http://localhost:2918/Orchard.Demo/ContentApi/GetAuthorizedById/1 from the browser? 

If you get a not found result then problem is no authorization, problem is you are accesing a resource that doesn't exist.

**Comment by jersiovic** [comment] 2017-04-27 15:48
Related to userinfo request. As you showed on first screenshot, it looks you forgot to Enable User Info Endpoint.

**Comment by jersiovic** [comment] 2017-04-27 15:59
I close the issue. Feel free to reopen the issue if I'm wrong on the cause of your problems

**Comment by yiji** [comment] 2017-04-28 01:39
I open url http://localhost:2918/Orchard.Demo/ContentApi/GetAuthorizedById/1  in the broswer，the resource doesn‘t exist，but it can go into “GetAuthorizedById” action。when i use jwt authorization，can't go into “GetAuthorizedById” action，I did not pass the authorization，redirect to login。
I add request header Authorization between Bearer and token has a  space is that wrong？

**Comment by jersiovic** [comment] 2017-04-28 05:02
I miss some scope baluew in your token request. Use the recommended values for scope that are shown in the openid application form, under Allow Passwod Flow. I added there recommended parameters for current configuration.

**Comment by yiji** [comment] 2017-04-28 05:34
@jersiovic ![default](https://cloud.githubusercontent.com/assets/6138770/25515407/f85257d2-2c16-11e7-8b28-92cc0c981eec.png)
 I have tried 
openid, profile, roles, offline_access
openid
profile
roles
offline_access
still doesn't work

**Comment by jersiovic** [comment] 2017-04-28 06:16
The role used by the user has Permissions.DemoAPIAccess enabled?

**Comment by jersiovic** [comment] 2017-04-28 06:37
I've tested it configuring a site from scratch and it works for me. Can you request a token for admin user? Does it work with that token?

**Comment by yiji** [comment] 2017-04-28 07:18
![default](https://cloud.githubusercontent.com/assets/6138770/25518353/fc792336-2c25-11e7-87cf-dc2bf763b948.png)

host is administrator
can you show me your configration?

**Comment by jersiovic** [comment] 2017-04-28 13:21
![image](https://cloud.githubusercontent.com/assets/4950766/25530241/e74c4542-2c25-11e7-88d6-59f599293e39.png)
![image](https://cloud.githubusercontent.com/assets/4950766/25530276/08205f7e-2c26-11e7-9bee-a1e93ec345c3.png)
![image](https://cloud.githubusercontent.com/assets/4950766/25530328/2c990fea-2c26-11e7-85e0-303e6ec086f6.png)
![image](https://cloud.githubusercontent.com/assets/4950766/25530353/4381681a-2c26-11e7-9f85-52b068dc3db5.png)

Hope it helps

**Comment by jersiovic** [comment] 2017-04-28 13:23
After changing general openid settings you need to restart orchard. Did you restarted it?

**Comment by jersiovic** [comment] 2017-04-28 13:26
You can also set Nlog logging level to Debug in NLog.config to get more info about what can be happening.

**Comment by yiji** [comment] 2017-04-29 01:43
[orchard-log-2017-04-29.txt](https://github.com/OrchardCMS/Orchard2/files/965818/orchard-log-2017-04-29.txt)
this is my NLog, i has rebuild Orchard.Cms.Web csproj taht equal restart orchard

**Comment by jersiovic** [comment] 2017-04-29 07:23
This line at log seems to explain what is causing your problem:
`Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'empty'. Did not match: validationParameters.ValidAudience: 'null' or validationParameters.ValidAudiences: 'http://localhost:2918'`
The point is why? Can you check that there is not any blank space on audiences setting and in your resource parameter on the token request?

**Comment by jersiovic** [comment] 2017-04-29 07:32
Remember to restart orchard after any change in audiences setting.

**Comment by yiji** [comment] 2017-04-29 12:02
I have set Audiences
![default](https://cloud.githubusercontent.com/assets/6138770/25555317/bdf1e44a-2d15-11e7-8e8a-5b62406469a9.png)

![default](https://cloud.githubusercontent.com/assets/6138770/25555325/f5e94dca-2d15-11e7-84c8-9086cae32a75.png)

![default](https://cloud.githubusercontent.com/assets/6138770/25555335/1b59db56-2d16-11e7-9d71-e00f108581ce.png)





**I search the error find [this](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/94)**
![default](https://cloud.githubusercontent.com/assets/6138770/25555344/7a544268-2d16-11e7-9c2b-98b613273826.png)


i changed openid startup.cs
![default](https://cloud.githubusercontent.com/assets/6138770/25555287/f49c23f8-2d14-11e7-8ea1-72c1868871dc.png)
i know this has issue,but now it's work

**Comment by PinpointTownes** [comment] 2017-04-29 16:52
The missing audience is likely caused by the fact you've added a space in the `resource` parameter (`resource [space]` != `resource`):

```
2017-04-29 09:25:43.3797|Default|0HL4EJQ61U0EN|0|AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware|INFO|The token request was successfully extracted from the HTTP request: {
  "grant_type": "password",
  "username": "host",
  "password": "[removed for security reasons]",
  "client_id": "unovoerp",
  "client_secret": "[removed for security reasons]",
  "scope": "openid offline_access profile roles",
  "resource ": "http://localhost:2918"
} 
```

**Closed** 2017-04-29 16:53 UTC
Labels: invalid, Orchard.OpenId

**Comment by yiji** [comment] 2017-04-30 00:14
yes,there is a space after resource request header,thank you,this is my fault.
