### ISSUE TITLE
TagHelpers defined in an external assembly do not work with AsModule projects.

### ISSUE THREAD

**Issue by dwschreyer** [OrchardCMS/Orchard2#696] opened 2017-04-15 02:38 UTC
I attempted a project as per the demo by [Sébastian Ros on On.NET](https://channel9.msdn.com/Shows/On-NET/Sbastien-Ros-Modular-ASPNET-apps). Great demo and works well.

However, it seems that when TagHelpers are defined in an external assembly they do not work with AsModule projects. If the TagHelper is defined in the AsModule project it works fine.

My objective is to allow the TagHelpers to be shared between the modules.

I have created a sample project to illustrate the issue: https://github.com/dwschreyer/OrchModuleTagHelperIssue

Could someone else please attempt to duplicate and confirm this issue?

**Comment by jtkech** [comment] 2017-04-15 07:20
In an mvc app, through the ApplicationPartManager, each assembly can provide mvc features if they define types of `IApplicationFeatureProvider<TFeature>`. E.g ViewComponentFeature, ControllerFeature, ViewsFeature, TagHelperFeature...

In our modular app, each tenant (you have at least one "Default" tenant) is a kind of a separate mvc app which manages its own ApplicationPartManager. But here we only provide types coming from the modules main assemblies. We are assuming (maybe wrongly) that mvc components (e.g a controller) are defined in modules main assemblies, not through another assembly which is not a Module.

>My objective is to allow the TagHelpers to be shared between the modules.

Note that if the other assembly is also build as a Module, i think it should work.

Otherwise, if it's really an external assembly, here the solution i see (needs to be checked) would be to define and use in your Module a TagHelper that just inherits of the one defined in your external assembly.

@sebastienros @Jetski5822 do we still think it's by design? Or do we need to also provide types coming from modules dependencies (those which reference an mvc primary assembly)? (as proposed in a previous PR which was using the way mvc uses to discover assembly parts).

Or, maybe we can wait for another similar issue but not related to TagHelper, this because we already have this one when some TagHelpers was defined in core projects (not through modules) ...

Best

**Comment by dwschreyer** [comment] 2017-04-15 08:05
Thanks for the explanation.

I have updated my sample project to implement my understanding of your suggestion by introducing another project called ExMClTagHelpers which references OrchardCore.AsModule. In turn Module1 references that project.

However, this does not work.

I have also tried other combinations which includes OrchModuleTagHelperIssue.Portal referencing ExMClTagHelpers. This did not have the desired effect either.

I think the issue here would limit the use of third-party controls such as Telerik as they would need to be referenced in a similar way.

**Comment by Jetski5822** [comment] 2017-04-15 12:57
@dwschreyer hey man, just cloned your repo.... Its doesnt restore... :(

But no worries, I will get it working!!!! Give me 30.

**Comment by Jetski5822** [comment] 2017-04-15 13:09
It would appear, that someone has taken all the Orchard code and put it on Nuget.... :/

**Comment by Jetski5822** [comment] 2017-04-15 13:35
@jtkech yeah this is a mistake, we should be pulling in all packages that reference MVC... I thought we were doing this???? or at least the code I originally wrote did this. Do you want to fix it?

@dwschreyer sorry about this man, it seems someone has published all the packages on nuget - once we update and fix the bug, the code will be available here:

> <add key="OrchardCore" value="https://www.myget.org/F/orchardcore-preview/api/v3/index.json" />

We wernt planning to release to Nuget until we are ready to ship. (sorry for the confusion)

**Comment by jtkech** [comment] 2017-04-15 14:53
Oh yes, when i do some tests in our solution, i pack modules and put them in a local feed. In your case you need a Nuget.config file (see in our repo for an example) and need to use this feed:

    <add key="SomeKeyName" value="https://www.myget.org/F/orchardcore-preview/api/v3/index.json" />

@Jetski5822 yes, no problem, first i will test these scenarios asap in our solution by using project references, then by using package references ...

Meanwhile, @dwschreyer can you check again your project with the above feed, first without any change, then with the proposed solutions.

Best.

**Comment by sebastienros** [comment] 2017-04-15 16:52
> we should be pulling in all packages that reference MVC

We stopped doing this because we were doing this to load the ShellBluePrint and it was fully transitive which means it was thousands of types, for nothing. We decided to only use the modules, and move the tag helpers to these modules. Also we are not registering the whole assemblies because it would expose controllers that are not part of the enabled features.

I can't think of another type than TagHelpers that could potentially be in a package that is not a module. Not sure it makes sense to share Controllers, ViewComponents need views so it's not possible (that's what modules provide, embedded views) so TagHelpers seem to be the only one as they don't require views.

Maybe we should just expose an option to register an assembly part on top of the ones we already discover.

**Comment by dwschreyer** [comment] 2017-04-15 18:37
Thanks for the quick turn around time on this issue - much appreciated.

@jtkech I have added the NuGet.config to my solution and updated the packages - *TagHelper still not working*.

Also did the following:

- Removed the experimental ExMClTagHelpers project.
- IServiceCollection functions as expected.
- Created a base controller in the ClTagHelpers project and that works for the module too.

I agree with @sebastienros that the idea of sharing controllers and views does not make sense. They are the reason the module exists. It would certainly be a requirement to share TagHelpers across modules.

Static resources such as .js, .css and images could be shared across modules in the main portal application. While module specific assets are already catered for in the module conventions which @sebastienros showed in the demo.

**Comment by jtkech** [comment] 2017-04-15 19:30
@dwschreyer just forked your repo and i got it working.

- I've create a `Nuget.config` file with the mentioned feed.
- I needed to replace in your *.csproj `Version="2.0.0-preview"` with `Version="2.0.0-preview-*"`. Then restart VS, restore packages ...
- Then in your `_ViewImports.cshtml` i just keep `@addTagHelper *, Module1`.
- Then in your Module1, as one of the suggestion, i've defined 2 other TagHelpers that just inherit of the ones defined in your external assemblies, e.g:

      [HtmlTargetElement("my-cl-h1")]
      [OutputElementHint("h1")]
      public class MyClH1TagHelper : ClTagHelpers.MyClH1TagHelper
      {
      }

- I will do a PR on your fork to show the changes.

![taghelpers](https://cloud.githubusercontent.com/assets/8586360/25066287/3a7cf60c-2222-11e7-96aa-ad11d11ba050.png)

Best.

**Comment by dwschreyer** [comment] 2017-04-15 19:38
@jtkech I did consider doing the wrapper. However, that is a less than optimal solution don't you think? For example, if we wanted to use Telerik controls in our modules, we would have to create this wrapper for each TagHelper in the library.

**Comment by jtkech** [comment] 2017-04-15 19:50
Yes, i understand, let me think about this.

Note: i can't push my change on your repo, forgot to fork it before. Let me know if you want to repro what i did, then i could re-do it on my own copy. I can also copy / paste here some simple changes i made.

**Comment by dwschreyer** [comment] 2017-04-15 19:52
I added the wrapper version to my project and did the other updates. All updated.

**Comment by jtkech** [comment] 2017-04-15 20:09
So, @sebastienros i remember a version i made in a PR where we were discovering assembly parts as mvc do but still filtering on enabled extension features ... But i agree, there was unnecessary types, not thousands but still 2 or 3 times more than currently.

>Maybe we should just expose an option to register an assembly part on top of the ones we already discover

So, the implicit option already there is that the assembly reference a primary mvc assembly. But we want to limit this to TagHelpers, and i think without having to parse all the dependency graph of each module.

I will think about this. Maybe by defining a marker in a module to import an external assembly and then also provide its types ...

@dwschreyer i will let you know my findings.

Best.

**Comment by jtkech** [comment] 2017-04-15 20:22
@dwschreyer just seen your updates.

In your Nuget.config you can remove the feed `Orchard2`, but you need this feed:

    <add key="OrchardCore" value="https://www.myget.org/F/orchardcore-preview/api/v3/index.json" />

Best.

**Comment by dwschreyer** [comment] 2017-04-15 20:28
Thanks for the update.

Removed Orchard2 from NuGet.config in my solution.

Is there something you would like me to look at?

**Comment by jtkech** [comment] 2017-04-15 20:38
And don't forget to add the above feed to be able to restore your packages. Then you can try the wrapped version on your side, but it's as you want.

Otherwise, nothing else at this time, i will try to implement something that allows to import easily external types without having to parse all the dependencies, without to define many wrapped classes ...

**Comment by dwschreyer** [comment] 2017-04-15 20:56
OK.

I believe my solution is up to date at the moment.

Question: Does this issue imply that I won't be able to use third-party controls (Telerik, etc) that rely on TagHelpers in the Orchard2 CMS?

**Comment by jtkech** [comment] 2017-04-15 21:08
Not necessarily, but we need to think more about this, we will let you know.

**Comment by sebastienros** [comment] 2017-04-15 21:38
Can we register another application part from the web app, or from a module. In this case a module or the main app could add an AssemblyPart that contains tag helpers.
If we need the ApplicationBuilder from the AddMvc call, then we really need to expose it somehow because I have already had an issue with this one the way it's not accessible from modules.

**Comment by jtkech** [comment] 2017-04-15 22:05
Yes, i will think about this.

Maybe in the `ConfigureServices()` of a module. Here i think you can resolve `ApplicationPartManger` which has been registered as a "shell" singleton by the `Orchard.Mvc` module, and then add an AssemblyPart. This through an extension method to do it easily.

**Comment by jtkech** [comment] 2017-04-15 22:11
But just seen that for each module, `ConfigureServices()` is called with a new empty service collection ...

**Comment by dwschreyer** [comment] 2017-04-16 04:02
I observed that behavior when I did my sample. My first thought was that this is by design as it would give the module isolation of its own required dependencies. Are you suggesting that this should not be the case? If you are, how would you achieve isolation for the module to resolve dependencies?

**Comment by jtkech** [comment] 2017-04-16 15:01
We want shell / tenant isolation, but you're right, somewhere else we separate services by module features. So, here we would need to also pass the tenant services collection to `ConfigureServices()` ...

Another solution would be that modules could register some kind of application part / types providers. Then in our custom `ShellFeatureApplicationPart` we could resolve them and add their types.

But just seen that we can do the following in the `Configure()` method of a module.

    var partManager = serviceProvider.GetRequiredService<ApplicationPartManager>();
    partManager.ApplicationParts.Add(new AssemblyPart(...));

I will try it on your project to see if it can solve your issue.

Note: i've done a PR on your repo to show the packages feed to use.

**Comment by sebastienros** [comment] 2017-04-16 16:32
Maybe add a TagHelperDescriptorProvider (don't recall the name exactly) so TagHelpers can be registered with DI.

**Comment by jtkech** [comment] 2017-04-16 18:06
Yes, if we want to limit it to TagHelpers, i will take a look on this.

Just for infos, in the @dwschreyer project, in the Module1 `Startup.Configure()`, i've tried the following that works. So, we could have an extension method to add an application part by providing a type, or maybe better just by providing the name of the assembly.

    using System.Reflection;
    ...
    using Microsoft.AspNetCore.Mvc.ApplicationParts;
    ...

        public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            var partManager = serviceProvider.GetRequiredService<ApplicationPartManager>();

            // by providing a type defined in the assembly
            //partManager.ApplicationParts.Add(new AssemblyPart(
            //    typeof(MyClH1TagHelper).GetTypeInfo().Assembly));

            // or by providing an assembly name
            // note: it's fast because the assembly is already loaded
            partManager.ApplicationParts.Add(new AssemblyPart(
                Assembly.Load(new AssemblyName("ClTagHelpers"))));

Then it works, what do you think?

**Comment by sebastienros** [comment] 2017-04-16 18:46
It's weird that it works ... or maybe it works for tag helpers but would not for other things, AFAIK the ApplicationParts is not using DI (but a builder) because it's used to gather data before the container is configured. I might be wrong.

But if it works as you are showing then this issue is closed, this is the way to register tag helpers coming from specific assemblies. We'll need to warn that any controller would be loaded too, and wouldn't benefint from feature/tenant isolation.

**Comment by Jetski5822** [comment] 2017-04-16 19:09
It would still have tenant isolation... as MVC is on the tenant level.... 

Could we not have something like this?

.AddSatelliteAssemblyTagHelpers()

This would look at the direct references on that assembly for all references to the ASPNet tag helpers dll, then register that assembly is an applicationpart?

I dunno, something thats cleaner and of more help.

**Comment by jtkech** [comment] 2017-04-16 20:09
I've put break points to see executing order

- Module ConfigureServices() => AddMvcCore() is done
- Module Configure() => Where we add an app part in our sample
- ShellFeatureApplicationPart Types are requested

There already are `IApplicationFeatureProvider<TFeature>` in `ApplicationManager.Features` and `PopulateFeature()` is called on them to lookup all `ApplicationParts` ... In the case of a `TagHelperFeature provider`, this is the way `TagHelper types` are added to the provider ...

And it works because it seems that it's done when needed, and you're right not through DI.

That's said, this also means that we could also use DI to allow modules to register some kind of assembly parts providers, then resolve them in `ShellFeatureApplicationPart` to provide only additional types which inherit from `TagHelper`.

@Jetski5822 good idea. Need to check, when an assembly only references `AspnetCore.Mvc`, then defines TagHelpers, if then `Mvc.TagHelpers` is a direct reference. We could also lookup its types to see if there are some that inherit (BaseType) from `TagHelper`.

Note: An external assembly could define TagHelpers through another assembly and so on ... So, 1st do we want to limit this to `TagHelpers`, and do we need to parse all the dependency graph or only provide types defined in the assembly.

**Comment by dwschreyer** [comment] 2017-04-16 20:44
@jtkech this is a great solution and makes total sense. Good work!

**Comment by jtkech** [comment] 2017-04-16 21:43
@dwschreyer thanks

@Jetski5822 you're right the external assembly has a direct reference on `TagHelper` and only if it defines a class which inherits from `TagHelper`.

But we still need to provide to `AddSatelliteAssemblyTagHelpers(SomeName)` e.g an assembly name parameter. This because when `Module1` references an external assembly, but uses it only in `_ViewImports.cshtml` with `@addTagHelper *, ExternalAssembly`, then Module1 does not have a direct reference on this external assembly, this by using `GetReferencedAssemblies()`.

So, we can't find this external assembly automatically. Maybe a solution with the `DependencyContext` but we would return back to all we don't want to re-do ...

So, we can easily provide an `AddSatelliteAssemblyTagHelpers(SomeName)` and, @Jetski5822 as you suggested, check if `TagHelper` is referenced. This, if it's not a problem to provide all types of this assembly. Otherwise, as said, i can implement a solution with DI which only adds types that inherits from `TagHelper`, and where we could use the same extension method name. Let me know what is better to do.

In both cases, we will not parse all the dependency graph, the user will need to use the extension method with the right assembly name where additional taghelpers are defined.

**Comment by dwschreyer** [comment] 2017-04-16 22:50
Updated my project and all is working great. Fantastic!

**Comment by jtkech** [comment] 2017-04-16 23:06
@dwschreyer cool!!!

So, it also works by doing exactly the same as in my previous solution where we add an `Assemblypart`, but by using a very simple custom `TagHelperAssemblyPart` (see below) in place of a regular `AssemblyPart`. Then we only provide additional types which inherit from `Taghelper`.

    public class TagHelperAssemblyPart : ApplicationPart, IApplicationPartTypeProvider
    {
        private Assembly _assembly;

        public TagHelperAssemblyPart(Assembly assembly)
        {
            _assembly = assembly ?? throw new ArgumentNullException(nameof(assembly));
        }

        public override string Name => _assembly.GetName().Name + ".TagHelper";

        public IEnumerable<TypeInfo> Types =>
            _assembly.ExportedTypes
            .Select(t => t.GetTypeInfo())
            .Where(t => t.IsSubclassOf(typeof(TagHelper)));
    }

So, we could easily provide an `AddSatelliteAssemblyTagHelpers(string assemblyName)` extension method. Or maybe `AddTagHelperAssemblyPart(string assemblyName)` according to the above class name. Let me know.

@sebastienros - @Jetski5822 if you think it's ok i will do a PR.

**Comment by jtkech** [comment] 2017-04-17 03:19
Without reconsidering the above solution, here just some other findings.

@sebastienros, not always (see below) but `ApplicationPartManager` is used by special services, this when they are instanciated (e.g `DefaultCompilerCacheProvider`) or through an interface method when needed. I think that's why we can add later application parts.

But I also seen some extensions which add features as services, e.g `builder.AddControllersAsServices()`. in this case the related `FeatureProvider(s)` in `partManager.Features` is used immediately to parse application parts and here to register discovered mvc features as services.

So, in this case you're right, all needed application parts would need to be already there. But i think that in this case (where DI is used) we could register later additional mvc features as services. So, maybe better to use `builder.AddTagHelpersAsServices()` and then easily register later other tagHelper types as services.

But, unfortunately, in `partManager.Features` i can see some feature providers (see below), but there is no default `TagHelperFeatureProvider`. And in the aspnet mvc repo i don't see any `TagHelperFeatureProvider` class which would need to derive from `IApplicationFeatureProvider<TagHelperFeature>`.

So, with this solution, right now we would also need to register all our own tag helpers as services, because they would not be registered automatically. Maybe an issue in mvc but notice that it is easy to define and register this missing `TagHelperFeatureProvider`.

    {Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider}
    {Microsoft.AspNetCore.Mvc.ViewComponents.ViewComponentFeatureProvider}
    {Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider}
    {Microsoft.AspNetCore.Mvc.Razor.Compilation.ViewsFeatureProvider}
    // But there is no {...TagHelperFeatureProvider}

That said, the solution in my previous comments is ok for me.

**Comment by sebastienros** [comment] 2017-04-17 15:21
@jtkech I assume you create a custom `ApplicationPart` because you don't want to import a full assembly or use `AssemblyPart`. I assume that can't hurt, even if it's not something we must do.

Just add this one then and close the issue.
And at the same time, please move the resource tag helpers back in the ResourceManagement project and add the TagHelperAssemblyPart in the module. The namespaces will also have to change where these tag helpers are used (like in many places), or maybe they will have the same namespace.

**Comment by jtkech** [comment] 2017-04-17 21:14
Ok, i will do a PR which will close this issue.

Maybe the longer part will be to move back tag helpers. As i remember there were also tag helpers in `Orchard.ContentManagement.Display`. I also remember that you created the `BaseShapeTagHelper` when you moved tag helpers. Maybe we could keep this class ...

---
For infos, above i said that `TagHelperFeatureProvider` was missing, this is true when working on aspnetcore 2.0, so maybe an issue here. But it is there when returning back to the master branch.

But, with `builder.AddTagHelpersAsServices()`, as said taghelpers are immediately discovered from app parts, but at this time `ShellFeatureApplicationPart` fails to return `Types`. So, we need to call it before adding our custom app part, and then we still need to register ourselves our taghelpers as services ...

**Comment by dazinator** [comment] 2017-04-18 12:15
Just commenting on the off chance that may be interested in a way to implement `addTagHelper` directives that support globbing on the assembly name too, not just the type name. i.e:

`@addTagHelper "*, Plugin.*"`

or

`@addTagHelper "*, *"`

This allows you to import all tag helpers, from a range of assemblies. 
[Info here](http://darrelltunnell.net/blog/2016/07/25/aspnet-core-taghelper-s-a-better-addtaghelper-type-resolver/) 

It can be useful in an extensible system where new modules are introducing `TagHelpers` that you want to automatically light up in View processing, without having to revisit the `add tag helper` directives.

**Comment by sebastienros** [comment] 2017-04-18 15:16
@dazinator thanks, didn't know about it

**Closed** 2017-04-18 20:41 UTC

**Comment by sebastienros** [comment] 2017-04-18 22:01
@dazinator talked with the TagHelper devs and they don't recommend it as it will kill the Tooling performance. Everytime build is called it would reload all assemblies to intellisense can work.

**Comment by dazinator** [comment] 2017-04-20 18:34
@sebastienros - Just wanted to add some clarification because it sounds like you are talking about tooling performance at design time (i.e intellisense etc).. Not sure who you spoke too, but AFAIK this globbing pattern will not work at all at design time - as globbing on the assembly name portion of an `addTagHelper` directive isn't supported by the design time tooling at all - probably for that very reason (i.e performance). 

The thing that provides this feature, is a custom `TagHelperTypeResolver` that you register at runtime, and it takes effect during runtime compilation of the razor view (which typically happens on first request to the view). 

Does Orchard allow you to install an extension at runtime? As this is where this feature might be useful and I can explain why. If not, it's probably not going to be useful to Orchard at all :-)
