### ISSUE TITLE
Edit views

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#652] opened 2017-04-03 12:29 UTC
With the latest version, it doesn't seem possible to make a change in a view and reload the page in the browser to see the changes.

Is there something I am missing? like launch the project with `dotnet watch`?

**Comment by jtkech** [comment] 2017-04-03 14:56
Oh yes, to see the change without re-launching the app, you need to make the change directly in the Packages folder under the app. But remember to do the final update in the OrchardCore.Modules folder because the Packages folder will be overwritten.

Note: In my working branch the packages folder is not hidden from the solution, but i think that right now it is hidden in the master branch.

Note: For infos, right now when you edit a view from the OrchardCore.Modules folder there is no intellisense. I have a workaround but need more tests before using it for all modules.

Best.

**Comment by sebastienros** [comment] 2017-04-03 17:31
@agriffard try to see if dotnet watch works. Otherwise we'll need to update the gulp pipeline which I'd rather not change.

**Comment by lukaskabrt** [comment] 2017-04-03 20:26
Launching Orchard.Cms.Web project with `dotnet watch run` doesn't work for me. It isn't watching for changes in *.cshtml files and it is by design [dotnet-watch does not watch *.cshtml files](https://github.com/aspnet/DotNetTools/issues/152), another issue with `dotnet watch` is, that it restarts the whole process.

jtkech's workaround with editing files directly in the Packages folder works. To enable IntelliSence, you have to include views in the project (IMO this change shouldn't be committed to the repository). It isn't ideal solution, because, as jtkech mentioned, views are overwritten every time you launch the project, but I don't have any better solution.

**Comment by jtkech** [comment] 2017-04-04 02:01
For infos, just seen [this blog post](http://www.natemcmaster.com/blog/2017/01/03/dotnet-watch-msbuild/). Maybe we can include custom items by using `<Watch Include="...">`, and target a custom task on file change (i hope without restarting the process) with `dotnet watch msbuild /t:CustomTask`.

I will try it when i have time.

**Comment by agriffard** [comment] 2017-04-10 13:10
See #686 for dotnet watch.cmd sample

**Closed** 2017-06-05 07:58 UTC
