### ISSUE TITLE
Features ordering

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#389] opened 2016-12-06 16:18 UTC
`GetEnabledFeaturesAsync()` needs to return the list of enabled features, including themes' features and base themes, ordered by dependency.
It's fine to have ExtensionManager not have features ordered, or care about having theme behave differently, but the `ShellManager` one has to be ordered.

@jtkech @Jetski5822

**Comment by Jetski5822** [comment] 2016-12-06 23:52
So a Theme is just treated like an extension, if you had this....

```
Name: Module1
# no dependencies

Name: Theme1
# no dependencies

Name: Theme2
DerivedTheme: Theme1
Dependencies: Theme1
```

The system would order this correctly based on Dependencies. It wouldnt matter that order Theme1, and Module1 were enabled, as there is no dependency.

Is there something im missing here?

**Comment by sebastienros** [comment] 2016-12-06 23:57
I'd say `BaseTheme` represent an implicit dependency, so you could also add this in `Dependencies` internally if you find this property.

**Comment by Jetski5822** [comment] 2016-12-07 00:07
Okay, then that give me an idea

**Comment by jtkech** [comment] 2016-12-07 01:52
Just coming back to this, so quickly as i remember.

Not to say where things need to be implemented but to be aware of some specificities i've seen when we want to reproduce what O1 is doing.

- So in O1, internally (or through some extensions methods) there is the `BaseTheme` implicit dependency and also the **implicit dependency of a theme on all modules** (mainly related to all around display management). This for ordering and also when checking for a dependency (as was doing the `HasDependency` used by extension manager in O1). Here i needed to add some extra code (that is not in O1) to implement a specific `HasDependency`.

- Around controller views (not shape) overriding, i also seen another implicit dependency where all themes are considered as a base theme of the admin theme (see #386). But here in O1 this is not implemented internally but specifically in `ThemeAwareViewEngine.cs`. So i've done the same.

- So, maybe too specific to implement internally theme implicit dependencies but we would need to check all places where we have to do things locally. About the `BaseTheme` dependency, it's a good idea to implement it as a normal dependency, but see above when all themes can be considered as a base theme of the admin theme, so ...

- Finally, see in #386 where i've updated for this PR the `GetEnabledFeatures()` extension method which was not ordered (in O1 the related extension is ordered). We could do it locally but because this extension method is used in different places, we would need to do the same in all of these places.

Best.

**Comment by jtkech** [comment] 2016-12-07 09:15
@sebastienros @Jetski5822 

> It's fine to have ExtensionManager not have features ordered, or care about having theme behave differently, but the ShellManager one has to be ordered.

Notice that in `ShellFeaturesManager` we have this. So currently they both return the same.

        public async Task<IEnumerable<IFeatureInfo>> GetEnabledFeaturesAsync()
        {
            return _extensionManager.GetEnabledFeatures(await GetCurrentShell());
        }

But anyway this ExtensionManagerExtension doesn't return an ordered collection. Here dependencies of an individual feature are ordered. But the final collection is not globally ordered!

        public static IEnumerable<IFeatureInfo> GetEnabledFeatures(this IExtensionManager extensionManager, ShellDescriptor shellDescriptor)
    {
        return shellDescriptor.Features.SelectMany(shellFeature => extensionManager.GetFeatureDependencies(shellFeature.Id)).Distinct();
    }

That's why in #386 i proposed this fix to implement it as in O1. Here we start from `GetExtensions().Features` which is ordered.

    public static IEnumerable<IFeatureInfo> GetEnabledFeatures(this IExtensionManager extensionManager, ShellDescriptor shellDescriptor)
    {
        return extensionManager.GetExtensions().Features.Where(f => shellDescriptor.Features.Any(sf => sf.Id == f.Id));
    }

But at this point we only have talked about explicit dependencies. let's talk about implicit ones.

- So there is the baseTheme implicit dependency but here at least you are missing one which is **the implicit dependencies of a theme on all modules**. In O1 this is done at the extension manager level.

- Note: in O1 there is another implicit dependency (but implemented locally) when resolving controller views paths. **Here each theme is considered as a base theme of the admin theme**.

- So, at the 1st level i agree with @Jetski5822, theme ordering is specific and not related to real dependencies, may vary according to the context and is tied to display management.

- But i was talking about this because, even it is better, i needed e.g in the shape table manager to add some code in its `HasDependency()` method to implement locally implicit dependencies. 

- But maybe only a few places are concerned and maybe already ok with the shape table manager which re-order things and what we will do locally with controller views paths.

- So, maybe ok to implement theme ordering only locally. If so we still need to implement the `BaseTheme` at a lower level and, as suggested by @Jetski5822, it could then be a regular dependency.

- **But i'm afraid that there are other places where the implicit theme dependency on all modules is important. E.g i think about an html filter from a theme which need to be called last**.

Here a piece of code grabbed from extension manager in O1 which may be helpful.

        internal static bool HasDependency(FeatureDescriptor item, FeatureDescriptor subject) {
            if (DefaultExtensionTypes.IsTheme(item.Extension.ExtensionType)) {
                if (DefaultExtensionTypes.IsModule(subject.Extension.ExtensionType)) {
                    // Themes implicitly depend on modules to ensure build and override ordering
                    return true;
                }

                if (DefaultExtensionTypes.IsTheme(subject.Extension.ExtensionType)) {
                    // Theme depends on another if it is its base theme
                    return item.Extension.BaseTheme == subject.Id;
                }
            }

            // Return based on explicit dependencies
            return item.Dependencies != null &&
                   item.Dependencies.Any(x => StringComparer.OrdinalIgnoreCase.Equals(x, subject.Id));
        }

Best.

**Comment by sebastienros** [comment] 2016-12-07 16:00
This piece of code should already be in the ordering logic. If it's not the case, then that's bad. Or at least in a separate class with a service that could be defined during the configuration of the web app, at the same time we call `AddModules`, just if @Jetski5822 wants to keep not having to handle extension types in a hard coded manner.

This piece of code could be implemented using multiple FeatureOrderStrategy classes that would each provide a custom behavior. It would implement an `ICompare<Feature, Feature>` and return `-1` or `1` to define the order, or `0` to say it can't order them, then the next comparer would be summoned. Implementations would be ordered by their priority. These would be used by the component returning the ordered features, not by the caller.

**Comment by Jetski5822** [comment] 2016-12-07 16:05
I have just pushed something to my branch to deal with adding BaseTheme as a implicit dependency

**Comment by Jetski5822** [comment] 2016-12-07 17:40
@jtkech on this PR https://github.com/OrchardCMS/Orchard2/pull/353 - Ordering is done in the extension manager.

Implicit dependencies are done when the features are built. Feature ordering at the moment is done by priority and dependency.

@sebastienros when I initially wrote this code, I was thinking about specifying a service... i.e. AddModules<ModuleExtensionProvider>("module.txt") and themes AddModules<ThemeExtensionProvider>("theme.txt") or something like that

Or have I miss read?

**Comment by sebastienros** [comment] 2016-12-07 18:57
@jtkech do you want me to merge this PR so you can test it? @Jetski5822 if nothing is broken compared to current master then let's merge it.

**Comment by jtkech** [comment] 2016-12-07 23:34
@Jetski5822 thanks, because what i'm working on is so tied to features ordering.
@sebastienros yes, i think it would be good.

**Comment by sebastienros** [comment] 2016-12-08 00:09
done

**Closed** 2016-12-08 19:59 UTC
