### ISSUE TITLE
SQLite Error 6: 'database table is locked'.

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/Orchard2#775] opened 2017-05-27 02:21 UTC
Master branch. Brand new site with SQLite.

After logging in to dashboard, enable and then disable a module, will result in this error.

**Comment by sebastienros** [comment] 2017-05-27 17:13
I can repro.

**Comment by jtkech** [comment] 2017-05-28 04:44
Me too and i was thinking about a concurrent write when redirecting ...

So, just for infos i could get it working with one of the following hack.

- By adding `_session.Dispose()` at the end of `ShellDescriptorManager.UpdateShellDescriptorAsync()`.

- Or by adding `_session.Dispose()` at the end of `ShellStateManager.UpdateShellState()` .

**Comment by sebastienros** [comment] 2017-05-28 17:32
Question is what is different with this request compared to the others. Specifically on disabling. Dispose should be called automatically when the request service scope is disposed. Looks more like another connection is still active. I'd like to understand what the actual issue is before it happens again somewhere else.

**Comment by jtkech** [comment] 2017-05-28 20:46
- If i 1st disable an enabled module, then **it also fails on enabling it**.

- Maybe the connexion is not correctly closed when redirecting.

I will let you know if i find something.

**Comment by sebastienros** [comment] 2017-05-29 00:16
hum, idea, when we mark the tenant to be recycled (by removing it from the shell contexts table), just before we redirect, then Dispose should be called on the container. Maybe it's not (anymore). check that.

**Comment by jtkech** [comment] 2017-05-29 00:45
Ok, i will take a look.

**Comment by sebastienros** [comment] 2017-05-29 01:55
This line should be called https://github.com/OrchardCMS/Orchard2/blob/0d9305e4279c0d0a02428289b4ebeebc96358c81/src/OrchardCore/Orchard.Environment.Shell/ShellHost.cs#L239

And I assume it is called correctly. However, this is the container, not the scoped provider, and the session is scoped. The session should be disposed when the scoped provider is, which means when the request is done. I assume ASP.NET is doing it by itself and we didn't write any code to do so. We can test it by added a service that is scoped and putting a break point in the this service's Dispoe method, and in the ShellHost where we dispose the container to see who comes first. Maybe we shouldn't dispose the container before all its scopes. But we also need to ensure the scope is correctly disposed on the redirect as it will Commit the transaction and free the connection.

**Comment by jtkech** [comment] 2017-05-29 02:19
- Yes, i already seen in `ShellHost.cs` that `context.Dispose()` is called.

- And in `ShellContext.cs` that `(ServiceProvider as IDisposable)?.Dispose()` is called.

- So here, for testing, i aslo tried to resolve `ISession` directly and then dispose it explicitly.

- Weird because, for example, if i call `_session.Dispose()` at the end of `ShellStateManager.UpdateShellState()`, this after the following line, then it works.

      await _eventBus.NotifyAsync<IShellDescriptorManagerEventHandler>(e => e.Changed(shellDescriptorRecord, _shellSettings.Name));
      _session.Dispose(); // added line


I will try it again tomorrow.

**Comment by jtkech** [comment] 2017-05-29 03:01
So, you're right, because it is registered at the scoped level, `ISession` is not disposed when calling `(ServiceProvider as IDisposable)?.Dispose()`. It seems that only disposable transient services are disposed here. Then, you're right, other services are only disposed at the end of their lifetime scope.

So, i think that `ISession` is correctly disposed at the end of the request, but the incoming redirection request arrives before the disposing ends and then the sqlite db / table lock was freed. I've seen a similar issue where people was using a retries / timeout pattern to fix it.

Note: When i resolve `ISession` myself, it seems that i get a new session, maybe because of the implementation factory which return a new session. After disposing it, in `UpdateShellDescriptorAsync()` i can see that `_session` is still not disposed.

**Comment by jtkech** [comment] 2017-05-29 03:24
To confirm the above, it seems to works if in `IShellDescriptorManagerEventHandler.Changed()` i do this.

            if (_shellContexts.TryRemove(tenant, out context))
            {
                var serviceProvider = _httpContextAccessor.HttpContext?.RequestServices;
                (serviceProvider as IDisposable)?.Dispose();
                context.Dispose();
            }

**Comment by sebastienros** [comment] 2017-05-29 05:09
I understand your last suggestion fixes the issue, but it might be more complex than it appears to have something correct. For instance, if an event changes the shell settings, we need to reload it, but does it actually mean we should dispose it right away? because some more code might run after that, for instance other middlewares, or maybe other things in the controller, and disposing all these might be an issue. So maybe we should not even dispose the container here but just remove it so that new requests create a new one, and wait for the very end of the request to dispose it. And maybe that;s the issue, that the container is disposed BEFORE the scoped provider.

Can you try in a separate application that a scoped services is correctly disposed on a redirect and we are not seeing a bug in ASP.NET (I hardly doubt of it). But then do the same thing by disposing the service container before the request is done. I will ask one of the devs what he thinks.

**Comment by jtkech** [comment] 2017-05-29 16:28
You're right, what i did was not even a suggestion, it was just for testing to better understand what happens.

Just tried to not dispose the `_shellContext`, it doesn't work.
Interesting, can't right now but i will do more tests this night.

Note: i'm afraid that we will be very limited if sqlite doesn't allow concurent write operations.

**Comment by sebastienros** [comment] 2017-05-29 17:03
Yes, Sqlite doesn't allow this, but that a good test as it should be fine. And if it works with Sqlite it works with everything ;)

**Comment by Skrypt** [comment] 2017-05-29 20:59
This is something I had already proposed to the team that does the Sqlite driver a while ago. But they need to follow the same design pattern for every database. SO, for supporting concurrent write operations I think what would be needed is an override of the driver itself as far as I can remember.

**Comment by jtkech** [comment] 2017-05-29 22:02
Just started again some tests. Scoped services seems to be disposed, with or without disposing the service container, and also on a redirection.

@Skrypt thanks for the suggestion, need more time to think about it ... Right now, i will do more tests around the special case of redirection to well understand what happens.

**Comment by sebastienros** [comment] 2017-05-30 15:09
Look at how Session is used after the container is disposed. Disposing it would dispose the Store, and the operations on Session will probably always need it to be not disposed. I could add some code in it to check if Store has been disposed, for diagnostics purpose.

**Comment by jtkech** [comment] 2017-05-30 16:41
Ok i will check it, i don't think that the store is disposed.

Maybe something related to the defered task middleware where we create a child scope, and how root containers are managed.

When i dispose the request services before or even after the execution of deferred tasks, it works.


                using (var scope = shellContext.CreateServiceScope())
                {
                    var deferredTaskEngine = scope.ServiceProvider.GetService<IDeferredTaskEngine>();

                    if (deferredTaskEngine != null && deferredTaskEngine.HasPendingTasks)
                    {
                        var context = new DeferredTaskContext(scope.ServiceProvider);
                        await deferredTaskEngine.ExecuteTasksAsync(context);
                        (httpContext?.RequestServices as System.IDisposable)?.Dispose();
                    }
                }

If i do the same at the end of `ModularTenantContainerMiddleware`, it doesn't work.

Interesting, i will continue this night.

**Comment by sebastienros** [comment] 2017-05-30 17:54
Talked to the DI devs, I will try something cleaner by ref counting the scopes and only disposing the container when there is no more pending requests on this one.

**Comment by sebastienros** [comment] 2017-05-30 18:34
Found the issue. Not yet worked on a fix.

The `ModularTenantContainerMiddleware` is responsible for initializing the shell context, creating and disposing scoped containers. It's also wrapping all middlewares created by the modules. The scope will be disposed after all middlewares have finished.

One of these middlewares is the deferred tasks one. When we change a shell context by enabling or disabling a feature, we create a deferred task to save the shell descriptors. The issue is that this deferred task will create a session in a separate scope, to write in the db. But the current request scope hasn't been disposed yet because it's wrapping the middlewares. In the end we get two open Sessions on the same request, and the second one can be released as the db is locked on the first one. So the request becomes interlocked. It should not impact other running requests in theory, but that still bad.

I think I will change how deferred tasks are working to ensure the main request scope is disposed before we run them.

**Comment by jtkech** [comment] 2017-05-30 20:42
Cool, so the session in the nested scope can't be released and so on.

I will test and review your PR soon.

**Closed** 2017-05-30 22:34 UTC
Labels: bug
